services:
 mysqldb:
  container_name: mysqldb
  image: mysql
  ports:
   - 3306:3306
  environment:
   MYSQL_DATABASE: order
   MYSQL_ROOT_PASSWORD: root

 order-app:
  image: order-app
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - 8080:8080
  environment:
   MYSQL_HOST: order
   MYSQL_USER: root
   MYSQL_PASSWORD: root
   MYSQL_PORT: 3306